### ISSUE TITLE
SuperCollider server crashes JVM

### ISSUE THREAD

**Issue by sjmurdoch** [overtone/overtone#230]
When I try starting Overtone with an internal Super Collider server, the JVM crashes:

```
$ lein repl
nREPL server started on port 50623
REPL-y 0.1.10
Clojure 1.3.0
    Exit: Control+D or (exit) or (quit)
Commands: (user/help)
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
          (user/sourcery function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
Examples from clojuredocs.org: [clojuredocs or cdoc]
          (user/clojuredocs name-here)
          (user/clojuredocs "ns-here" "name-here")
user=> (use 'overtone.live)
--> Loading Overtone...
--> Booting internal SuperCollider server...
Invalid memory access of location 0x160 rip=0x11e70757c
Exception in thread "Thread-2" java.net.SocketException: The transport's socket appears to have lost its connection to the nREPL server
                                 transport.clj:95 clojure.tools.nrepl.transport/bencode[fn]
                                 transport.clj:95 clojure.tools.nrepl.transport/bencode[fn]
                                 transport.clj:42 clojure.tools.nrepl.transport/fn-transport[fn]
                                    core.clj:1836 clojure.core/binding-conveyor-fn[fn]
                                      AFn.java:18 clojure.lang.AFn.call
                              FutureTask.java:303 java.util.concurrent.FutureTask$Sync.innerRun
                              FutureTask.java:138 java.util.concurrent.FutureTask.run
                      ThreadPoolExecutor.java:895 java.util.concurrent.ThreadPoolExecutor$Worker.runTask
                      ThreadPoolExecutor.java:918 java.util.concurrent.ThreadPoolExecutor$Worker.run
                                  Thread.java:680 java.lang.Thread.run
Bye for now!clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 139}
    at clojure.core$ex_info.invoke(core.clj:4327)
    at leiningen.core.eval$fn__1963.invoke(eval.clj:213)
    at clojure.lang.MultiFn.invoke(MultiFn.java:231)
    at leiningen.core.eval$eval_in_project.invoke(eval.clj:283)
    at leiningen.repl$start_server.invoke(repl.clj:117)
    at leiningen.repl$server$fn__4421.invoke(repl.clj:173)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:617)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1788)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:621)
    at clojure.core$bound_fn_STAR_$fn__4102.doInvoke(core.clj:1810)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:680)
```

project.clj is

```
(defproject tutorial "1.0"
  :dependencies [ [org.clojure/clojure "1.5.1"]
                  [overtone "0.8.1"] ])
```

**Comment by frenchy64** [comment]
This should be closed since we don't have an internal server any longer.
