### ISSUE TITLE
JVM crashes if overtone.live required and quil.core/defsketch called 

### ISSUE THREAD

**Issue by lpil** [overtone/overtone#313]
Hi all

Box info:

```
64bit Debian Jessie Linux
org.clojure/clojure "1.5.1"
overtone "0.9.1"
quil "2.2.4"
```

I'm trying to create a simple quil sketch that makes noises with Overtone, but I'm having problems with the JVM crashing. Here is my program:

``` Clojure
(ns lans-syn.core
  (:require [overtone.live]
            [quil.middleware :as m]
            [quil.core :as q]))

(def starting-state
  {})

(defn setup []
  (q/frame-rate 30)
  starting-state)

(defn update [state]
  state)

(defn draw [state]
  (q/ellipse (/ (q/width) 2) (/ (q/height) 2) 10 10))

(q/defsketch lans-syn
  :title "Louis' ANS Synthesizer"
  :size [720 500]
  :setup setup
  :update update
  :draw draw
  :middleware [m/fun-mode])
```

When I run it from the repl the JVM crashes immediately after loading Overtone, see here:

```
louis ~/projects/lans-synthesizer [master *] $ lein repl
nREPL server started on port 32970 on host 127.0.0.1
REPL-y 0.3.0
Clojure 1.5.1
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use 'lans-syn.core)
--> Loading Overtone...
  ********************************************************** 
      WARNING: JVM argument TieredStopAtLevel=1 is active, and may 
      lead to reduced performance. This happens to currently be the 
      default lein setting:

      https://github.com/technomancy/leiningen/pull/1230

      If you didn't intend this JVM arg to be specified, you can turn 
      it off in your project.clj file or your global 
      ~/.lein/profiles.clj file by adding the key-val

      :jvm-opts ^:replace [] 
      ********************************************************** 
--> Booting internal SuperCollider server...
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
no message buffer overruns
no message buffer overruns
no message buffer overruns
jackdmp 1.9.10
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 95
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio2
creating alsa driver ... hw:UDJ6|hw:UDJ6|256|2|44100|0|0|nomon|swmeter|-|32bit
configuring for 44100Hz, period = 256 frames (5.8 ms), buffer = 2 periods
ALSA: final selected sample format for playback: 24bit little-endian
ALSA: use 2 periods for playback
ALSA: Cannot open PCM device alsa_pcm for capture. Falling back to playback-only mode
*** ERROR: dlsym load err '/home/louis/projects/lans-synthesizer/target/native/linux/x86_64/libscsynth.so: undefined symbol: load'
Found 0 LADSPA plugins
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 256
--> Connecting to internal SuperCollider server...
--> Connection established
JackDriver: max output latency 11.6 ms

    _____                 __
  / __  /_  _____  _____/ /_____  ____  ___
  / / / / | / / _ \/ ___/ __/ __ \/ __ \/ _ \
/ /_/ /| |/ /  __/ /  / /_/ /_/ / / / /  __/
\____/ |___/\___/_/   \__/\____/_/ /_/\___/

  Collaborative Programmable Music. v0.9.1


Hello Louis, just take a moment to pause and focus your creative powers...

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f700c80e274, pid=19954, tid=140118554396416
#
# JRE version: OpenJDK Runtime Environment (7.0_65-b32) (build 1.7.0_65-b32)
# Java VM: OpenJDK 64-Bit Server VM (24.65-b04 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.5.3
# Distribution: Debian GNU/Linux unstable (sid), package 7u71-2.5.3-2
# Problematic frame:
# C  [libpthread.so.0+0xa274]  pthread_mutex_lock+0x4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/louis/projects/lans-synthesizer/hs_err_pid19954.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
JackEngine::XRun: client = SuperCollider was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = SuperCollider was not finished, state = Triggered
JackEngine::XRun: client = SuperCollider was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
Unknown error...
terminate called after throwing an instance of 'Jack::JackTemporaryException'
  what():  
Exception in thread "Thread-4" clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 134}
  at clojure.core$ex_info.invoke(core.clj:4327)
  at leiningen.core.eval$fn__3532.invoke(eval.clj:226)
  at clojure.lang.MultiFn.invoke(MultiFn.java:231)
  at leiningen.core.eval$eval_in_project.invoke(eval.clj:326)
  at clojure.lang.AFn.applyToHelper(AFn.java:167)
  at clojure.lang.AFn.applyTo(AFn.java:151)
  at clojure.core$apply.invoke(core.clj:619)
  at leiningen.repl$server$fn__7443.invoke(repl.clj:201)
  at clojure.lang.AFn.applyToHelper(AFn.java:159)
  at clojure.lang.AFn.applyTo(AFn.java:151)
  at clojure.core$apply.invoke(core.clj:617)
  at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1788)
  at clojure.lang.RestFn.invoke(RestFn.java:425)
  at clojure.lang.AFn.applyToHelper(AFn.java:163)
  at clojure.lang.RestFn.applyTo(RestFn.java:132)
  at clojure.core$apply.invoke(core.clj:621)
  at clojure.core$bound_fn_STAR_$fn__4102.doInvoke(core.clj:1810)
  at clojure.lang.RestFn.invoke(RestFn.java:397)
  at clojure.lang.AFn.run(AFn.java:24)
  at java.lang.Thread.run(Thread.java:745)
SocketException The transport's socket appears to have lost its connection to the nREPL server
  clojure.tools.nrepl.transport/bencode/fn--4287/fn--4288 (transport.clj:95)
  clojure.tools.nrepl.transport/bencode/fn--4287 (transport.clj:95)
  clojure.tools.nrepl.transport/fn-transport/fn--4261 (transport.clj:42)
  clojure.core/binding-conveyor-fn/fn--4107 (core.clj:1836)
  java.util.concurrent.FutureTask.run (FutureTask.java:262)
  java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:615)
  java.lang.Thread.run (Thread.java:745)
Bye for now!
```

However, if I comment out the call to quil.core/defsketch it does not crash after Overtone finishes loading.

Changing the draw function or not using the quil middleware does not seem to have any effect.

What am I doing wrong here? (related to #293 ?)

Thanks,
Louis

**Comment by kaosbeat** [comment]
I'm having similar problems, I tried open-JDK as well as oracle-JDK, versions 6, 7 and 8 always the same problem.
It seems to be overtone & quil related, but I haven't found the trigger yet, it seems random.

Kasper

**Comment by nblumoe** [comment]
I also had issues, although I did not yet verify that it's the same as described above. My workaround was to always use `defsketch` first, before loading overtone. Like this:
https://github.com/nblumoe/clj-tunes/blob/master/src/clj_tunes/core.clj#L4

**Comment by RutenkolkC** [comment]
I have the same problem on my linux kubuntu 18.04 machine with clojure 1.9.

I don't really like necroing, but for advertising seamless integration with quil, there is little documentation in this project when it comes to quil. In fact, all the info I can find are github-issues. Most of them closed.

The workaround of @nblumoe seems to work on my machine as well. Mad kudos. I would have given up on this otherwise.

Since this is a few years old now, is there any interest in at least mentioning this workaround in the wiki for example?
