### ISSUE TITLE
Installation problems.

### ISSUE THREAD

**Issue by prozz** [overtone/overtone#429]
I'm on fresh installation of Ubuntu 18.04.2 LTS (Bionic). I followed quickstart instruction, but cannot make Overtone work (please find log from REPL session below). My SuperCollider (version 3.8.0) works well and it makes a sine wave sound. I found on wiki that last supported version was 3.7.2, but since that page wasn't updated for more than two years, I'm not sure if that's still the case or if it was abandoned.

Are there any packages I'm missing to make Overtone work?
How can I recompile native libraries to work properly?
Or maybe should I downgrade SuperCollider?

If you need more info about my setup, please let me know.

```
~/github/insane-noises                                                                                                                                      
▶ lein repl      
nREPL server started on port 45617 on host 127.0.0.1 - nrepl://127.0.0.1:45617
REPL-y 0.4.3, nREPL 0.6.0
Clojure 1.9.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_201-b09
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

insane-noises.core=> (use 'overtone.live)
--> Loading Overtone...
--> Booting internal SuperCollider server...
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
no message buffer overruns
no message buffer overruns
no message buffer overruns
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/ReverbUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/UnpackFFTUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/LFUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/DelayUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/NoiseUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/GrainUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/FilterUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/OscUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/DiskIO_UGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/PV_ThirdParty.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/ChaosUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/PhysicalModelingUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/PanUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/UnaryOpUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/DynNoiseUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/FFT_UGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/ML_UGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/TriggerUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/TestUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/IOUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/BinaryOpUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/GendynUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/MulAddUGens.so
*** ERROR: API Version Mismatch: native/linux/x86_64/plugins/DemandUGens.so
JackDriver: client name is 'Overtone'
SC_AudioDriver: sample rate = 48000,000000, driver's block size = 1024
Exception in World_OpenUDP: bind: Address already in use
--> Connecting to internal SuperCollider server...
--> Connection established
JackDriver: max output latency 42,7 ms
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
*** ERROR: SynthDef overtone.sc.4a6/snd-server-info not found
FAILURE IN SERVER /s_new SynthDef not found
java.util.concurrent.TimeoutException: deref! timeout error. Dereference took longer than 5000 ms whilst attempting to fetch server information
	at overtone.helpers.lib$deref_BANG_.invokeStatic(lib.clj:275)
	at overtone.helpers.lib$deref_BANG_.invoke(lib.clj:261)
	at overtone.helpers.lib$deref_BANG_.invokeStatic(lib.clj:269)
	at overtone.helpers.lib$deref_BANG_.invoke(lib.clj:261)
	at overtone.sc.info$server_info.invokeStatic(info.clj:73)
	at overtone.sc.info$server_info.invoke(info.clj:39)
	at overtone.sc.info$server_num_input_buses.invokeStatic(info.clj:130)
	at overtone.sc.info$server_num_input_buses.invoke(info.clj:123)
	at overtone.sc.bus$allocate_hw_audio_buses.invokeStatic(bus.clj:346)
	at overtone.sc.bus$allocate_hw_audio_buses.invoke(bus.clj:344)
	at overtone.libs.deps$satisfy_STAR_$execute_tasks__3252$fn__3259.invoke(deps.clj:85)
	at overtone.libs.deps$satisfy_STAR_$execute_tasks__3252.invoke(deps.clj:84)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6747)
	at clojure.core$reduce.invoke(core.clj:6730)
	at overtone.libs.deps$satisfy_STAR_.invokeStatic(deps.clj:95)
	at overtone.libs.deps$satisfy_STAR_.invoke(deps.clj:77)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2028)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Agent$Action.doRun(Agent.java:114)
	at clojure.lang.Agent$Action.run(Agent.java:163)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
May 11, 2019 9:56:12 PM clojure.lang.Reflector invokeMatchingMethod
SEVERE: Exception in dependency handler: :overtone.sc.bus/allocate-hw-audio-busses

*** ERROR: SynthDef overtone.sc.4a6/snd-server-info not found
FAILURE IN SERVER /s_new SynthDef not found
*** ERROR: SynthDef over1ee/__internal-wall-clock__ not found
FAILURE IN SERVER /s_new SynthDef not found
java.util.concurrent.TimeoutException: deref! timeout error. Dereference took longer than 5000 ms whilst attempting to fetch server information
	at overtone.helpers.lib$deref_BANG_.invokeStatic(lib.clj:275)
	at overtone.helpers.lib$deref_BANG_.invoke(lib.clj:261)
	at overtone.helpers.lib$deref_BANG_.invokeStatic(lib.clj:269)
	at overtone.helpers.lib$deref_BANG_.invoke(lib.clj:261)
	at overtone.sc.info$server_info.invokeStatic(info.clj:73)
	at overtone.sc.info$server_info.invoke(info.clj:39)
	at overtone.sc.info$server_num_input_buses.invokeStatic(info.clj:130)
	at overtone.sc.info$server_num_input_buses.invoke(info.clj:123)
	at overtone.studio.mixer$start_io_mixers$fn__10965.invoke(mixer.clj:92)
	at overtone.sc.machinery.server.comms$with_server_sync.invokeStatic(comms.clj:117)
	at overtone.sc.machinery.server.comms$with_server_sync.invoke(comms.clj:99)
	at overtone.studio.mixer$start_io_mixers.invokeStatic(mixer.clj:91)
	at overtone.studio.mixer$start_io_mixers.invoke(mixer.clj:88)
	at overtone.libs.deps$satisfy_STAR_$execute_tasks__3252$fn__3259.invoke(deps.clj:85)
	at overtone.libs.deps$satisfy_STAR_$execute_tasks__3252.invoke(deps.clj:84)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6747)
	at clojure.core$reduce.invoke(core.clj:6730)
	at overtone.libs.deps$satisfy_STAR_.invokeStatic(deps.clj:95)
	at overtone.libs.deps$satisfy_STAR_.invoke(deps.clj:77)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2028)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Agent$Action.doRun(Agent.java:114)
	at clojure.lang.Agent$Action.run(Agent.java:163)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
May 11, 2019 9:56:17 PM clojure.lang.Reflector invokeMatchingMethod
SEVERE: Exception in dependency handler: :overtone.studio.mixer/start-bus-mixers

CompilerException java.lang.Exception: The following deps took too long (20 seconds) to be satisfied: :server-ready, compiling:(overtone/live.clj:6:1) 

insane-noises.core=> 

```

**Comment by hlolli** [comment]
Did you upgrade within a project? Try deleting target and native
directories and let me know if the same thing happens of not.

**Comment by prozz** [comment]
Inside `insane-noises` I did delete both dirs as you suggested and same thing happened.
I also just tried to clone overtone repo and use repl there, executing `(use 'overtone.live)` ends with same errors.

**Comment by hlolli** [comment]
Ok for now use external synth, I will look into this soon! Thanks a lot for
the report!

**Comment by hlolli** [comment]
(boot-external-server) I mean via (use overtone.core)

**Comment by hlolli** [comment]
So I looked into this with Docker

here's my dockerfile with ubuntu 18.10

```Dockerfile
FROM ubuntu:18.10
MAINTAINER Hlöðver Sigurðsson <hlolli@gmail.com>
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
RUN apt-get update
RUN apt-get install -y software-properties-common curl jackd xvfb alsa-utils
RUN add-apt-repository ppa:openjdk-r/ppa && apt-get install -y openjdk-11-jre

RUN curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > ./lein
RUN chmod +x ./lein
RUN echo '(defproject insane-noises "0.1.0-SNAPSHOT" :description "FIXME: write description" :dependencies [[org.clojure/clojure "1.10.0"] [overtone "0.10.4"]])' > project.clj
RUN ./lein deps
```

And here's the result
```
$ docker run hlolli/overtone_ubuntu:1.0 sh -c "jackd -r -d dummy -r 48000 & echo \"(use 'overtone.live)\" | ./lein repl"
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in non-realtime mode
self-connect-mode is "Don't restrict self connect requests"
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
nREPL server started on port 41737 on host 127.0.0.1 - nrepl://127.0.0.1:41737
REPL-y 0.4.3, nREPL 0.6.0
Clojure 1.10.0
OpenJDK 64-Bit Server VM 11.0.2+9-Ubuntu-3ubuntu118.10.3
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use 'overtone.live)
--> Loading Overtone...
SC FFT global init: cosTable initialised.
  ********************************************************** 
       WARNING: JVM argument TieredStopAtLevel=1 is active, and may 
       lead to reduced performance. This happens to currently be the 
       default lein setting:

       https://github.com/technomancy/leiningen/pull/1230

       If you didn't intend this JVM arg to be specified, you can turn 
       it off in your project.clj file or your global 
       ~/.lein/profiles.clj file by adding the key-val

       :jvm-opts ^:replace [] 
       ********************************************************** 
--> Booting internal SuperCollider server...
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
JackDriver: client name is 'Overtone'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 1024
--> Connecting to internal SuperCollider server...
--> Connection established
JackDriver: max output latency 42.7 ms

    _____                 __
   / __  /_  _____  _____/ /_____  ____  ___
  / / / / | / / _ \/ ___/ __/ __ \/ __ \/ _ \
 / /_/ /| |/ /  __/ /  / /_/ /_/ / / / /  __/
 \____/ |___/\___/_/   \__/\____/_/ /_/\___/

   Collaborative Programmable Music. v0.10.4


Hey Root, I feel something magical is only just beyond the horizon...

nil
user=> Bye for now!
````

The internal synth boots without a problem.

Could you post me the result of

```
ldd native/linux/x86_64/libscsynth.so
```
?

**Comment by prozz** [comment]
So funny thing is that your external boot suggestion didn't work for me. Error was:

`--> Connecting to external SuperCollider server: 127.0.0.1:45067
Execution error at overtone.sc.machinery.server.connection/external-connection-runner (connection.clj:156).
Error: unable to connect to externally booted server after 50 attempts.
Make sure that you have Server.options.maxLogins set to greater than 1 in startup file (startup.scd).
Or if you're on Windows, make sure that the Windows defender isn't blocking the scsynth.exe
`
It make my try some other commands, eventually all worked after firing SuperCollider IDE, booting server inside there and using `(connect-external-server)` with proper port.

My `startup.scd` in both cases looked like this:
`▶ cat ~/.config/SuperCollider/startup.scd 
Server.default.options.maxLogins = 64;
`
I don't really know what I'm doing when it comes to SuperCollider, so I just took this snippet from some gist, please note word `default`, it's missing from Overtone's error message and may be confusing.

After looking at your docker example I realized I was upgrading to 18.04 and not installing it from scratch. It went smoothly, but may be a reason of this problem. Anyway here is the `ldd`:

`~/github/overtone  master ✔                                                                                        
▶ ldd native/linux/x86_64/libscsynth.so.1
	linux-vdso.so.1 (0x00007ffd35ff4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff19e0e1000)
	libsndfile.so.1 => native/linux/x86_64/libsndfile.so.1 (0x00007ff19e381000)
	libjack.so.0 => native/linux/x86_64/libjack.so.0 (0x00007ff19e334000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff19ded9000)
	libstdc++.so.6 => native/linux/x86_64/libstdc++.so.6 (0x00007ff19dd0f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff19d971000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff19d759000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff19d368000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff19e2e5000)
	libFLAC.so.8 => native/linux/x86_64/libFLAC.so.8 (0x00007ff19d2e4000)
	libogg.so.0 => native/linux/x86_64/libogg.so.0 (0x00007ff19e328000)
	libvorbis.so.0 => native/linux/x86_64/libvorbis.so.0 (0x00007ff19d2a9000)
	libvorbisenc.so.2 => native/linux/x86_64/libvorbisenc.so.2 (0x00007ff19d1fa000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff19cfdb000)
	libcelt0.so.2 => native/linux/x86_64/libcelt0.so.2 (0x00007ff19e30c000)
	libopus.so.0 => native/linux/x86_64/libopus.so.0 (0x00007ff19cf7b000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007ff19cd2e000)
	libmvec.so.1 => /lib/x86_64-linux-gnu/libmvec.so.1 (0x00007ff19cb04000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007ff19c87e000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ff19c658000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007ff19c43c000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007ff19c121000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007ff19bf0c000)
`

Happy to help, thanks a lot for your time :)

**Comment by hlolli** [comment]
add `Server.local.options.maxLogins = 10;` to ~/.config/SuperCollider to fix the login bug, it's a known bug for years, time to create a ticket on Supercollider for this.

**Comment by hlolli** [comment]
sorry didn't read all, see you did that, I guess that default key shouldn't be there, both local and Server.options (without default or local) work

**Comment by prozz** [comment]
`local` indeed works. Without anything like this:
```
▶ cat ~/.config/SuperCollider/startup.scd
Server.options.maxLogins = 10;
```

Inside IDE output is:

```
init_OSC
compiling class library...
initPassOne started
	NumPrimitives = 712
initPassOne done
	compiling dir: '/usr/share/SuperCollider/SCClassLibrary'
	compiling dir: '/usr/share/SuperCollider/Extensions'
	pass 1 done
	numentries = 1218428 / 18916950 = 0.064
	5785 method selectors, 3270 classes
	method table size 19232016 bytes, big table size 151335600
	Number of Symbols 14888
	Byte Code Size 465138
	compiled 458 files in 0.22 seconds

Info: 3 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
Class tree inited in 0.01 seconds
ERROR: Message 'options' not understood.
RECEIVER:
class Server (0x55f1d566a800) {
  instance variables [19]
    name : Symbol 'Server'
    nextclass : instance of Meta_ServerBoot (0x55f1d5210600, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : instance of Array (0x55f1d45d31c0, size=1, set=2)
    methods : instance of Array (0x55f1d566a980, size=147, set=8)
    instVarNames : instance of SymbolArray (0x55f1d566ba00, size=32, set=4)
    classVarNames : instance of SymbolArray (0x55f1d566be00, size=7, set=2)
    iprototype : instance of Array (0x55f1d566bb80, size=32, set=5)
    cprototype : instance of Array (0x55f1d566bec0, size=7, set=3)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 122
    classFlags : Integer 0
    maxSubclassIndex : Integer 123
    filenameSymbol : Symbol '/usr/share/SuperCollider/SCClassLibrary/Common/Control/Server.sc'
    charPos : Integer 5421
    classVarIndex : Integer 325
}
ARGS:
PATH: /home/prozz/.config/SuperCollider/startup.scd

PROTECTED CALL STACK:
	Meta_MethodError:new	0x55f1d485ed40
		arg this = DoesNotUnderstandError
		arg what = nil
		arg receiver = Server
	Meta_DoesNotUnderstandError:new	0x55f1d4860d00
		arg this = DoesNotUnderstandError
		arg receiver = Server
		arg selector = options
		arg args = [  ]
	Object:doesNotUnderstand	0x55f1d432b100
		arg this = Server
		arg selector = options
		arg args = nil
	a FunctionDef	0x55f1d43c1e48
		sourceCode = "Server.options.maxLogins = 10;

 "
	a FunctionDef	0x55f1d477e980
		sourceCode = "<an open Function>"
	Function:prTry	0x55f1d4ac7a40
		arg this = a Function
		var result = nil
		var thread = a Thread
		var next = nil
		var wasInProtectedFunc = false
	
CALL STACK:
	DoesNotUnderstandError:reportError   0x55f1d4479658
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x55f1d4479708
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x55f1d44797b8
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x55f1d4479868
		arg this = <instance of DoesNotUnderstandError>
	Function:protect   0x55f1d447e5a8
		arg this = <instance of Function>
		arg handler = <instance of Function>
		var result = <instance of DoesNotUnderstandError>
	Interpreter:executeFile   0x55f1d43c2748
		arg this = <instance of Interpreter>
		arg pathName = "/home/prozz/.config/SuperCol..."
		arg args = [*0]
		var result = nil
		var saveExecutingPath = nil
	ArrayedCollection:do   0x55f1d447e778
		arg this = [*2]
		arg function = <instance of Function>
		var i = 1
	Platform:loadStartupFiles   0x55f1d447ec18
		arg this = <instance of LinuxPlatform>
	LinuxPlatform:startup   0x55f1d447f188
		arg this = <instance of LinuxPlatform>
	Main:startup   0x55f1d4230e88
		arg this = <instance of Main>
		var didWarnOverwrite = false
^^ The preceding error dump is for ERROR: Message 'options' not understood.
RECEIVER: Server


SCDoc: Indexing help-files...
SCDoc: Indexed 1869 documents in 0.58 seconds
```

**Comment by hlolli** [comment]
Perfect, I will try to document that maxLogins error better, I'll change that error message to include .local. going to push 0.10.5 tonight or next days, because of the max-buffers bug, if you hit that, just add that into your ~/.overtone/config.clj as a workaround.

**Comment by prozz** [comment]
What I meant by 'it works' was that `Server.local.options.maxLogins` makes my SuperCollider IDE server boot, while `Server.options.maxLogins` doesn't. Original issue is still there :)

**Comment by prozz** [comment]
So I tried your Dockerfile, but changed Ubuntu version to 18.04 as this is what I got on my laptop here. Still works. It has to be some weird stuff going on with my machine: missing deps or bad config, I'm not sure what exactly. Let keeps it closed, but let me know if you have any idea for a fix ;) Cheers!

**Comment by prozz** [comment]
Final update from me: I decided to update my Ubuntu further, up to 19.04 which include SuperCollider 3.10.0. All works like a charm, problems gone.
