### ISSUE TITLE
(use 'overtone.live) loading error on windows 10

### ISSUE THREAD

**Issue by nevraydin** [overtone/overtone#453]
I'm tryin to loading overtone on Windows 10 machine and take compiling error below.

This is project.clj content;

```
(defproject overtone-tutorial "1.0.0"
  :dependencies [[overtone/overtone "0.10.3"]]
  :native-path "native"
  :source-paths ["src"])
```

```
>lein --version
Leiningen 2.9.3 on Java 1.8.0_144 Java HotSpot(TM) 64-Bit Server VM
```

```
lein repl
nREPL server started on port 2639 on host 127.0.0.1 - nrepl://127.0.0.1:2639
REPL-y 0.4.4, nREPL 0.6.0
Clojure 1.9.0-alpha17
Java HotSpot(TM) 64-Bit Server VM 1.8.0_144-b01
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use 'overtone)
FileNotFoundException Could not locate overtone__init.class or overtone.clj on classpath.  clojure.lang.RT.load (RT.java:458)

user=> (use 'overtone.live)
--> Loading Overtone...
CompilerException java.lang.RuntimeException: Unable to resolve symbol: impulse in this context, compiling:(overtone/sc/info.clj:23:17)
```

**Comment by markus-wa** [comment]
I've been having similar issues, unfortunately it's currently not supported: https://github.com/overtone/overtone/issues/447

I tried to get it working but ultimately I switched to linux anyway. If you are interested in the progress I made I can share it.

**Comment by markus-wa** [comment]
btw, for most usecases you should be able to use an external server: https://github.com/overtone/overtone/wiki/Connecting-scsynth#connecting-to-an-external-server

**Comment by FishAres** [comment]
@markus-wa I might be missing something but the (boot-external-server) etc. commands don't seem to exist for me after loading  `(use 'overtone.core)` (i.e. they throw a symbol-not-resolved error). Do you maybe know what the issue may be?

**Comment by markus-wa** [comment]
@FishAres - That's strange, I've never used `(boot-external-server)` as I've always done this manually in via SC UI. `(connect-external-server)` should be available though.

Not sure what the issue could be.

**Comment by dickensas** [comment]
I have installed SuperCollider 3.11.1 

Started the SuperCollider

```
*** Welcome to SuperCollider 3.11.1. *** For help press Ctrl-D.
SCDoc: Indexing help-files...
SCDoc: Indexed 1345 documents in 1.3 seconds
Booting server 'localhost' on address 127.0.0.1:57110.

Device options:
  - MME : Microsoft Sound Mapper - Input   (device #0 with 2 ins 0 outs)
  - MME : Headset Microphone (Plantronics   (device #1 with 2 ins 0 outs)
  - MME : Internal Microphone (Conexant I   (device #2 with 2 ins 0 outs)
  - MME : Microsoft Sound Mapper - Output   (device #3 with 0 ins 2 outs)
  - MME : Headset Earphone (Plantronics B   (device #4 with 0 ins 2 outs)
  - MME : Speaker (Conexant ISST Audio)   (device #5 with 0 ins 6 outs)
  - Windows DirectSound : Primary Sound Capture Driver   (device #6 with 2 ins 0 outs)
  - Windows DirectSound : Headset Microphone (Plantronics Blackwire 3220 Series)   (device #7 with 2 ins 0 outs)
  - Windows DirectSound : Internal Microphone (Conexant ISST Audio)   (device #8 with 2 ins 0 outs)
  - Windows DirectSound : Primary Sound Driver   (device #9 with 0 ins 2 outs)
  - Windows DirectSound : Headset Earphone (Plantronics Blackwire 3220 Series)   (device #10 with 0 ins 2 outs)
  - Windows DirectSound : Speaker (Conexant ISST Audio)   (device #11 with 0 ins 6 outs)
  - Windows WASAPI : Speaker (Conexant ISST Audio)   (device #12 with 0 ins 2 outs)
  - Windows WASAPI : Headset Earphone (Plantronics Blackwire 3220 Series)   (device #13 with 0 ins 2 outs)
  - Windows WASAPI : Internal Microphone (Conexant ISST Audio)   (device #14 with 2 ins 0 outs)
  - Windows WASAPI : Headset Microphone (Plantronics Blackwire 3220 Series)   (device #15 with 2 ins 0 outs)
  - Windows WDM-KS : Microphone Array (Conexant ISST Audio capture)   (device #16 with 2 ins 0 outs)
  - Windows WDM-KS : Stereo Mix (Conexant ISST Stereo Mix)   (device #17 with 2 ins 0 outs)
  - Windows WDM-KS : Output 1 (Conexant ISST Audio output)   (device #18 with 0 ins 2 outs)
  - Windows WDM-KS : Output 2 (Conexant ISST Audio output)   (device #19 with 0 ins 6 outs)
  - Windows WDM-KS : Input (Conexant ISST Audio output)   (device #20 with 2 ins 0 outs)
  - Windows WDM-KS : Headset Microphone (Plantronics Blackwire 3220 Series)   (device #21 with 2 ins 0 outs)
  - Windows WDM-KS : Headset Earphone (Plantronics Blackwire 3220 Series)   (device #22 with 0 ins 2 outs)

Requested devices:
  In (matching device NOT found):
  - (null)
  Out (matching device NOT found):
  - (null)

Selecting default system input/output devices

Booting with:
  In: MME : Headset Microphone (Plantronics
  Out: MME : Headset Earphone (Plantronics B
  Sample rate: 44100.000
  Latency (in/out): 0.013 / 0.091 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Requested notification messages from server 'localhost'
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
```

Check Java version from Git Bash

```
java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode)
```

Create a project

```
$ lein new insane-noises
Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this release.
Generating a project called insane-noises based on the 'default' template.
The default template is intended for library projects, not applications.
To see other templates (app, plugin, etc), try `lein help new`.
```

modify project.clj

```
(defproject insane-noises "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"][overtone "0.10.6"]]
  :repl-options {:init-ns insane-noises.core})
```

Start REPL

```
$ lein repl
Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this release.
nREPL server started on port 59071 on host 127.0.0.1 - nrepl://127.0.0.1:59071
REPL-y 0.4.4, nREPL 0.7.0
Clojure 1.10.1
Java HotSpot(TM) Client VM 1.8.0_161-b12
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

insane-noises.core=>
```

Boot the server

```
insane-noises.core=> (use 'overtone.core)
--> Loading Overtone...
--> Please boot a server to start making noise:
    * (boot-server)             ; boot default server (honours config)
    * (boot-internal-server)    ; boot an internal server
    * (boot-external-server)    ; boot an external server
    * (connect-external-server) ; connect to an existing external server

nil
```

Connect to the existing server

```
insane-noises.core=> (connect-external-server)
--> Connecting to external SuperCollider server: 127.0.0.1:57110
java.util.concurrent.TimeoutException: deref! timeout error. Dereference took longer than 5000 ms whilst whilst turning server notifications on
        at overtone.helpers.lib$deref_BANG_.invokeStatic(lib.clj:275)
        at overtone.helpers.lib$deref_BANG_.invoke(lib.clj:261)
        at overtone.helpers.lib$deref_BANG_.invokeStatic(lib.clj:269)
        at overtone.helpers.lib$deref_BANG_.invoke(lib.clj:261)
        at overtone.sc.machinery.server.connection$server_notifications_on.invokeStatic(connection.clj:64)
        at overtone.sc.machinery.server.connection$server_notifications_on.invoke(connection.clj:33)
        at overtone.sc.machinery.server.connection$setup_connect_handlers$handler_fn__5493.invoke(connection.clj:120)
        at overtone.libs.handlers$run_handler.invokeStatic(handlers.clj:135)
        at overtone.libs.handlers$run_handler.invoke(handlers.clj:129)
        at overtone.libs.handlers$run_one_shot_handlers.invokeStatic(handlers.clj:201)
        at overtone.libs.handlers$run_one_shot_handlers.invoke(handlers.clj:195)
        at overtone.libs.handlers$emhs_handle_async_one_shots$fn__3125.invoke(handlers.clj:208)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Execution error at overtone.libs.deps/wait-until-deps-satisfied (deps.clj:184).
The following deps took too long (20 seconds) to be satisfied: :server-ready
```

Run a Demo

```
insane-noises.core=> (demo (sin-osc))
Execution error (IllegalArgumentException) at overtone.sc.node/eval5819$fn$G (node.clj:21).
No implementation of method: :to-sc-id of protocol: #'overtone.sc.node/to-sc-id* found for class: nil
```


Please help me

**Comment by markus-wa** [comment]
Check your logs (i think in~/.overtone/logs but I don't remember for sure

**Comment by dickensas** [comment]
Adopt JDK https://adoptopenjdk.net/ solved my issue 

```
insane-noises.core=> (connect-external-server)
--> Connecting to external SuperCollider server: 127.0.0.1:57110
--> Connection established
:happy-hacking
insane-noises.core=> (demo (sin-osc))
#<synth-node[loading]: insane-noisesabd/audition-synth 21>
```
