### ISSUE TITLE
Unable to load `overtone.live` namespace on MacOS

### ISSUE THREAD

**Issue by jumarko** [overtone/overtone#474]
I'm experimenting with overtone 0.10.6 on MacOS 11.2.3 (Big Sur) using leiningen and JDK 14.
I'm getting this error when I add `(:require [overtone.live :as ol])` to my ns declaration.
```
Syntax error (NullPointerException) compiling at (overtone/jna_path.clj:37:1).
Cannot invoke "org.eclipse.aether.RepositorySystem.newLocalRepositoryManager(org.eclipse.aether.RepositorySystemSession, org.eclipse.aether.repository.LocalRepository)" because "system" is null

;; Detailed stacktrace
1. Caused by java.lang.NullPointerException
   Cannot invoke
   "org.eclipse.aether.RepositorySystem.newLocalRepositoryManager(org.eclipse.aether.RepositorySystemSession,
   org.eclipse.aether.repository.LocalRepository)" because "system" is null

                 maven.clj:  197  clojure.tools.deps.alpha.util.maven/make-session
                 maven.clj:  194  clojure.tools.deps.alpha.util.maven/make-session
                 maven.clj:   94  clojure.tools.deps.alpha.extensions.maven/eval18401/fn/fn
               session.clj:   23  clojure.tools.deps.alpha.util.session/retrieve
               session.clj:   14  clojure.tools.deps.alpha.util.session/retrieve
                 maven.clj:   94  clojure.tools.deps.alpha.extensions.maven/eval18401/fn
              MultiFn.java:  244  clojure.lang.MultiFn/invoke
                 alpha.clj:  192  clojure.tools.deps.alpha/expand-deps/fn
                 alpha.clj:  191  clojure.tools.deps.alpha/expand-deps
                 alpha.clj:  169  clojure.tools.deps.alpha/expand-deps
                 alpha.clj:  237  clojure.tools.deps.alpha/resolve-deps
                 alpha.clj:  217  clojure.tools.deps.alpha/resolve-deps
                 alpha.clj:  231  clojure.tools.deps.alpha/resolve-deps
                 alpha.clj:  217  clojure.tools.deps.alpha/resolve-deps
                bundle.clj:  198  badigeon.bundle/extract-native-dependencies
                bundle.clj:  182  badigeon.bundle/extract-native-dependencies
              jna_path.clj:   38  overtone.jna-path/eval19081
              jna_path.clj:   38  overtone.jna-path/eval19081
             Compiler.java: 7177  clojure.lang.Compiler/eval
             Compiler.java: 7636  clojure.lang.Compiler/load
                   RT.java:  381  clojure.lang.RT/loadResourceScript
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  459  clojure.lang.RT/load

```

I searched through issues and found this which looks related: https://github.com/overtone/overtone/issues/349
I tried `(connect-external-server)` but got this error:
```
--> Connecting to external SuperCollider server: 127.0.0.1:57110
Execution error at overtone.sc.machinery.server.connection/external-connection-runner (connection.clj:167).
Error: unable to connect to externally booted server after 50 attempts.
Make sure that you have Server.local.options.maxLogins set to greater than 1 in startup file (startup.scd).
Or if you're on Windows, make sure that the Windows defender isn't blocking the scsynth.exe
```

After that, I tried to run `(require '[overtone.live :as ol])` again and got a different error than before: 
```
Exception in thread "Thread-31" java.lang.NullPointerException: Cannot invoke "clojure.lang.IFn.invoke()"
	at clj_native.structs$byref.invokeStatic(structs.clj:178)
	at clj_native.structs$byref.invoke(structs.clj:174)
	at overtone.sc.machinery.server.native$scsynth.invokeStatic(native.clj:237)
	at overtone.sc.machinery.server.native$scsynth.invoke(native.clj:230)
	at overtone.sc.machinery.server.connection$internal_booter.invokeStatic(connection.clj:205)
	at overtone.sc.machinery.server.connection$internal_booter.invoke(connection.clj:200)
	at overtone.sc.machinery.server.connection$boot_internal_server$fn__20451.invoke(connection.clj:225)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by Jacob-Kroeze** [comment]
I had good luck with 
 ```
% java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

**Comment by plexus** [comment]
Hi @jumarko , I know it's been a while but any chance you could try the latest version? We dropped the internal SuperCollider, so you do have to install that manually now (e.g. through brew), but the result is that issues like the above should no longer be possible.

Please open a new issue if you still encounters problems getting started.

Thanks a lot!
