### ISSUE TITLE
Native dependencies don't load with Java 7 on Linux

### ISSUE THREAD

**Issue by technomancy** [overtone/overtone#86]
Getting this with Leiningen 1 and 2, but this particular issue doesn't occur with OpenJDK 6:

```
~/src/overtone $ lein1 version
Leiningen 1.7.1 on Java 1.7.0-release OpenJDK 64-Bit Server VM
~/src/overtone $ lein1 repl
REPL started; server listening on localhost port 52908
user=> (use 'overtone.live)
java.lang.UnsatisfiedLinkError: Unable to load library 'scsynth_jna': libjack.so.0: cannot open shared object file: No such file or directory
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:164)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:237)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:200)
    at com.sun.jna.Native.register(Native.java:1013)
    at supercollider.internal.ScSynthLibrary.<clinit>(ScSynthLibrary.java:100)
    at supercollider.ScSynth.run(ScSynth.java:110)
    at overtone.sc.machinery.server.connection$internal_booter.invoke(connection.clj:160)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:722)
Exception in thread "Thread-5" java.lang.UnsatisfiedLinkError: supercollider.internal.ScSynthLibrary.scsynth_jna_init()I
    at supercollider.internal.ScSynthLibrary.scsynth_jna_init(Native Method)
    at supercollider.ScSynth.run(ScSynth.java:110)
    at overtone.sc.machinery.server.connection$internal_booter.invoke(connection.clj:160)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:722)
Exception The following deps took too long to be satisfied: :server-ready  overtone.libs.deps/wait-until-deps-satisfied (deps.clj:148)
```

**Comment by hlolli** [comment]
For what it's worth `libjack.so.0` means that libscsynth.so wasn't able to find the `libjack.so.0` from $LD_LIBRARY_PATH, so it's a native operation outside of JNA. I did experiment with providing this shared dynamic in JNA, it may work in isolated cases, but connecting to jack2 server from client loaded with different `libjack.so.0` will cause strange errors and crashes. That means jack2 will keep being a dependency for useing Overtone and $LD_LIBRARY_PATH must point to a directory where `libjack.so.0` is located (by installing `qjackctl` on most if not all linux package managers, will do this automatically).
